### ISSUE TITLE
e.data.search is not a function

### ISSUE THREAD

**Issue by Binternet** [pelias/pelias-dashboard#12]
Dashboard numbers are not showing and this error is shown in the console:

```
Uncaught TypeError: e.data.search is not a function
    at handler (application.js:1325)
```

**Comment by Binternet** [comment]
More errors from the docker log:

```
pelias-dashboard | 172.16.1.9 - - [15/Apr/2018 07:24:19] "GET /pelias HTTP/1.1" 200 1855 0.0033
pelias-dashboard | {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No feature for name [pelias]"}],"type":"illegal_argument_exception","reason":"No feature for name [pelias]"},"status":400}
pelias-dashboard | 400
pelias-dashboard | Thin web server (v1.6.4 codename Gob Bluth)
pelias-dashboard | Maximum connections set to 1024
pelias-dashboard | Listening on 0.0.0.0:3030, CTRL+C to stop
pelias-dashboard | 172.16.1.9 - - [15/Apr/2018 07:24:21] "GET /views/list.html HTTP/1.1" 200 493 0.0009
pelias-dashboard | 172.16.1.9 - - [15/Apr/2018 07:24:21] "GET /views/text.html HTTP/1.1" 200 175 0.0009
pelias-dashboard | 172.16.1.9 - - [15/Apr/2018 07:24:21] "GET /views/meter.html HTTP/1.1" 200 336 0.0010
pelias-dashboard | ================================================================================
pelias-dashboard | scheduler caught exception:
pelias-dashboard | undefined method `[]' for nil:NilClass
pelias-dashboard | /opt/pelias/dashboard/jobs/es_metrics.rb:38:in `block in <top (required)>'
pelias-dashboard | /usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
pelias-dashboard | /usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
pelias-dashboard | /usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
pelias-dashboard | ================================================================================
pelias-dashboard | ================================================================================
pelias-dashboard | scheduler caught exception:
pelias-dashboard | undefined method `[]' for nil:NilClass
pelias-dashboard | /opt/pelias/dashboard/jobs/es_metrics.rb:38:in `block in <top (required)>'
pelias-dashboard | /usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
pelias-dashboard | /usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
pelias-dashboard | /usr/local/bundle/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
pelias-dashboard | ================================================================================
```

**Comment by theobolo** [comment]
Same here +1

**Comment by takeoffs-mu** [comment]
Might be related to this, https://github.com/Smashing/smashing/wiki/Uncaught-TypeError:-e.data.search-is-not-a-function

**Comment by billsinc** [comment]
Might be related to this, https://github.com/Smashing/smashing/wiki/Uncaught-TypeError:-e.data.search-is-not-a-function

**Comment by orangejulius** [comment]
I think this error is caused by failures to reach Elasticsearch for whatever reason. As it's been a while, if anyone is seeing this problem, please open a new issue.
